import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // eslint-plugin-react cannot auto-detect the React version under ESLint 10.
    settings: { react: { version: "19" } },
  },
  {
    rules: {
      // Icons are Google Material Symbols (filled), generated by `pnpm icons`.
      // shadcn/ui adds components with Phosphor imports: swap them.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@phosphor-icons/react",
              message: "Use Material icons from @/components/icons.",
            },
            {
              name: "lucide-react",
              message: "Use Material icons from @/components/icons.",
            },
          ],
          patterns: [
            {
              group: ["@phosphor-icons/react/*"],
              message: "Use Material icons from @/components/icons.",
            },
          ],
        },
      ],
    },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    ".claude/**",
  ]),
])

export default eslintConfig
