#!/usr/bin/env node
/**
 * Generates components/icons.tsx from Google's official Material Symbols SVGs
 * (package @material-symbols/svg-400) and from Simple Icons for brand logos.
 *
 *   pnpm icons
 *
 * To add an icon: find its name on https://fonts.google.com/icons (snake_case,
 * e.g. "arrow_outward"), add an entry to MATERIAL below, run `pnpm icons` and
 * import it from "@/components/icons". Never edit components/icons.tsx by hand.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const require = createRequire(import.meta.url)
const root = join(dirname(fileURLToPath(import.meta.url)), "..")

/** Material Symbols family and fill. "outlined" + filled = classic Material Icons "Filled". */
const FAMILY = "outlined"
const FILLED = true

/** Export name (without the "Icon" suffix) → Material Symbols name. */
const MATERIAL = {
  // Interface
  Add: "add",
  ArrowBack: "arrow_back",
  ArrowForward: "arrow_forward",
  ArrowOutward: "arrow_outward",
  Check: "check",
  CheckCircle: "check_circle",
  ChevronDown: "keyboard_arrow_down",
  ChevronLeft: "chevron_left",
  ChevronRight: "chevron_right",
  ChevronUp: "keyboard_arrow_up",
  Close: "close",
  Computer: "computer",
  DarkMode: "dark_mode",
  Dashboard: "dashboard",
  Error: "error",
  Home: "home",
  Info: "info",
  Language: "language",
  LightMode: "light_mode",
  Link: "link",
  LinkOff: "link_off",
  Logout: "logout",
  Menu: "menu",
  OpenInNew: "open_in_new",
  ProgressActivity: "progress_activity",
  Remove: "remove",
  Search: "search",
  Settings: "settings",
  Warning: "warning",
  // Status & communication
  Build: "build",
  Campaign: "campaign",
  Celebration: "celebration",
  Chat: "chat",
  Forum: "forum",
  Mail: "mail",
  Notifications: "notifications",
  // Product
  Alarm: "alarm",
  StarShine: "star_shine",
  Badge: "badge",
  BarChart: "bar_chart",
  Bolt: "bolt",
  Brush: "brush",
  Casino: "casino",
  ConfirmationNumber: "confirmation_number",
  CreditCard: "credit_card",
  Diamond: "diamond",
  Dns: "dns",
  DocumentScanner: "document_scanner",
  Favorite: "favorite",
  Gavel: "gavel",
  Groups: "groups",
  History: "history",
  HowToReg: "how_to_reg",
  Hub: "hub",
  Lock: "lock",
  Mic: "mic",
  Monitoring: "monitoring",
  Palette: "palette",
  Public: "public",
  ReceiptLong: "receipt_long",
  RocketLaunch: "rocket_launch",
  Schedule: "schedule",
  Shield: "shield",
  ShieldPerson: "shield_person",
  SmartToy: "smart_toy",
  Speed: "speed",
  Star: "star",
  Timer: "timer",
  Translate: "translate",
  TravelExplore: "travel_explore",
  Tune: "tune",
  Verified: "verified",
  VerifiedUser: "verified_user",
  WavingHand: "waving_hand",
  WorkspacePremium: "workspace_premium",
}

/** Brand logos from Simple Icons (CC0). Export name (without "Icon") → slug. */
const BRANDS = {
  Discord: "discord",
}

function readMaterial(name) {
  const file = `${name}${FILLED ? "-fill" : ""}.svg`
  const path = require.resolve(`@material-symbols/svg-400/${FAMILY}/${file}`)
  const svg = readFileSync(path, "utf8")
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1])
  if (!paths.length) throw new Error(`No path found in ${file}`)
  return { viewBox: "0 -960 960 960", paths }
}

function readBrand(slug) {
  const svg = readFileSync(
    require.resolve(`simple-icons/icons/${slug}.svg`),
    "utf8"
  )
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1])
  return { viewBox: "0 0 24 24", paths }
}

const entries = [
  ...Object.entries(MATERIAL).map(([n, s]) => [n, readMaterial(s), s]),
  ...Object.entries(BRANDS).map(([n, s]) => [n, readBrand(s), `${s} (Simple Icons)`]),
].sort(([a], [b]) => a.localeCompare(b))

const body = entries
  .map(
    ([name, { viewBox, paths }, source]) =>
      `/** ${source} */\nexport const ${name}Icon = createIcon("${name}Icon", "${viewBox}", ${JSON.stringify(paths)})`
  )
  .join("\n\n")

const output = `// Generated by scripts/generate-icons.mjs — do not edit by hand, run \`pnpm icons\`.
// Material Symbols (${FAMILY}, ${FILLED ? "filled" : "unfilled"}, weight 400) © Google, Apache License 2.0.
// Brand icons from Simple Icons, CC0 1.0.
import * as React from "react"

export type IconProps = React.ComponentProps<"svg">
export type Icon = React.ComponentType<IconProps>

function createIcon(displayName: string, viewBox: string, paths: string[]) {
  function Icon(props: IconProps) {
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox={viewBox}
        fill="currentColor"
        aria-hidden="true"
        focusable="false"
        {...props}
      >
        {paths.map((d) => (
          <path key={d} d={d} />
        ))}
      </svg>
    )
  }
  Icon.displayName = displayName
  return Icon
}

${body}
`

writeFileSync(join(root, "components/icons.tsx"), output)
console.log(`components/icons.tsx: ${entries.length} icons`)
